apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
  namespace: default
  labels:
    app: quarkus-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: quarkus-app

