apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-cloudflare
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yipkaitsun/cd_repo.git
    targetRevision: main
    path: keycloak-manifests/overlays/cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

