---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: vpn
data:
  WEBPASSWORD: "dev-admin-password"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: vpn
spec:
  rules:
  - host: pihole-dev.vpn.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 80

