---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: vpn
data:
  PEERS: "3"
  SERVERURL: "172.31.14.164"  # Update with your actual server IP after deployment
  MTU: "1420"

