---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: vpn
data:
  PEERS: "3"  # Fewer peers for dev environment
  SERVERURL: "18.183.57.208"  # Dev EC2 IP (update as needed)

