apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: quarkus-app
        env:
        - name: APP_ENV
          value: "development"
        - name: QUARKUS_LOG_LEVEL
          value: "DEBUG"

