apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: docker.io/kaitsunyip0/quarkus-app
  newTag: latest

labels:
- pairs:
    environment: dev
  includeSelectors: false

