---
# This is a placeholder - generate actual certificate on K3s server
# See instructions in keycloak-manifests/README.md
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
  namespace: keycloak
type: kubernetes.io/tls
data:
  # Generate with:
  # openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  #   -keyout tls.key -out tls.crt \
  #   -subj "/CN=18.183.57.208/O=Keycloak"
  # kubectl create secret tls keycloak-tls --cert=tls.crt --key=tls.key -n keycloak --dry-run=client -o yaml
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2RENDQWRHZ0F3SUJBZ0lVRXhwTGV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREFBCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

