---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: vpn
data:
  WEBPASSWORD: "CHANGE-THIS-SECURE-PASSWORD"  # ⚠️ CHANGE THIS!
# Pi-hole ingress removed for security
# Access Pi-hole via port-forward only:
# kubectl port-forward -n vpn svc/pihole-web 8888:80
# Then open: http://localhost:8888/admin

