---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: vpn
data:
  PEERS: "10"  # More peers for production
  SERVERURL: "18.183.57.208"  # Production EC2 IP (update as needed)

