---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        env:
        - name: KC_HTTPS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTPS_ENABLED
        - name: KC_HTTPS_CERTIFICATE_FILE
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTPS_CERTIFICATE_FILE
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTPS_CERTIFICATE_KEY_FILE
        - name: KC_HTTPS_PORT
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTPS_PORT
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/keycloak-tls
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: keycloak-tls

