apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: keycloak-patch.yaml
  - path: postgres-patch.yaml
  - path: service-patch.yaml

