---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_HOSTNAME: "keycloak.yourcompany-sso.com"  # CHANGE THIS to your CloudFlare domain
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge"  # Important: CloudFlare handles SSL
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: dev-admin-password  # CHANGE THIS in production!

